apiVersion: v1
kind: Pod
metadata:
  name: solar-system-deployment
  label:
    app: solar-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
        name: solar-system-container
        image: siddharth67/solar-system
        imagePullPolicy: Always
        ports:
          containerPort: 80
