apiVersion: v1
kind: Service
metadata: 
  name: solar-system-service
  label:
    app: solar-system
spec:
  selector:
    matchLabels:
      app: solar-system
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort   
